# Infinite Bot 3.1.0 - ViewManager(视图增强附属)
#
# 注：视图增强为其它附属（如消息互通）的增强前置附属，如您需要对该类附属进行功能增强，
#   请将本附属与其依赖附属安装在同一服务器下
#
# Tips: 附属前置 InteractiveChat 自带游戏内物品展示功能(以下均为默认关键字)
#   - 手持物品展示 [i] / [item]
#   - 背包展示 [inv] / [inventory]
#   - 末影箱展示 [e] / [ender]

# 默认关键字列表 []表示监听范围 ()表示权限等级
#   - 我的背包 [全局] (无)
#   - 我的末影箱 [全局] (无)
#   - 当前在线 [全局] (无)
key-word:
  my-bag: '我的背包'
  my-ender: '我的末影箱'
  online: '当前在线'