# Infinite Bot 3.1.0 - MessageManager(自定义消息附属)
#
# 内置变量(正在添加中)
# > 特殊（特殊内置变量以{#name}的形式调用，部分仅可在指定 show-type 中使用）
# - {#sender}: @消息触发者
#     show-type: command 不可用
# - {#reply}: 将该条消息设置为回复消息
#     show-type: command 不可用
#     !注意!：{#reply}后不能直接接{#sender}，否则qq会吞掉@。
#       可以采用 '{#reply}{#sender}{#sender}' 或 '{#reply}文字{#sender}' 的方式避免此问题
# - {#content}: 标识请求api接口返回的消息
#     仅 show-type: api 可用
# > 通用（通用内置变量以{name}的形式调用，允许在所有 show-type 中使用）
# - {senderName}: 消息触发者qq名称，若无法获取则返回发送者qq

# 消息文件储存的相对路径
#   若不存在则会自动创建
folder: '/message'

# 图片资源最长连接时间 单位：秒
# 超时即认为图片资源加载失败（网络状况不佳
get-image-timeout: 10

# 图片资源代理设置
proxy:
  enable: false
  host: 'localhost'
  port: 7890

# 触发被限制时进行提示
notice-when-limit: true

# 自定义静态变量，在 content 节点中使用 {名称} 调用
# 优先级：papi变量 > 自定义静态变量
# !! 暂不支持嵌套使用
custom-placeholder:
  自定义变量: 'Hello World'
