# Infinite Bot 3.1.0 - DefenceManager(白名单登录验证码功能)
#
# 可用指令: ’清空缓存 [数值]‘ [任意] (管理)
#     可清空数值以内的所有攻击者记录(允许尝试加入服务器
#
# Notice:
#   - 为防止机器人被屏蔽无法回复群消息，该验证可与机器人发起临时会话/私聊完成
#   - 验证码长度会随着短期内玩家尝试登录次数增加，初始为4，最高可达6

# 原版白名单玩家可直接进入
white-list: true

# 验证码有效时间 (单位: 分钟)
limit: 3

# 若开启此选项 则已在AuthMe注册的玩家可直接进入(若服务器未装载AuthMe则需关闭)
#   // 已移除对登录插件的额外支持，若您却有需求，可联系作者进行拓展
# auth-me: false

# 已绑定玩家在退群时是否清除其绑定数据
remove-on-leave: false

# 防压测
# 本附属仅提供原始防压测功能，如有必要请您使用·更专业的防压测插件
defence:
  enable: false
  tips: true # 是否给予踢出提示
  threshold: 100 # 检测阈值

# 若无回复则请先确认机器人群消息是否被屏蔽
success: '绑定成功，直接进入游戏即可！'
failure: '您的验证码已失效或不存在'

# 非白名单玩家加入服务器时拒绝信息
messages:
  - '&7&l请先加入Q群: &a&l607994785'
  - "&7&l在群内发送 '&e&l&n验证 正版/离线 %code%'"
  - '&7&l即可让当前账号[&b&l%player%&7&l]&f&l进入服务器'
  - '&7&l此验证码有效期至：%time%&8&l[到期重新登入获取]'
  - '&4&l注册完成之前请勿泄露自己用户名'
